language: node_js
node_js:
  - '0.11'
script:
  - npm test
  - ./travis.sh
env:
  global:
    - secure: "Xj3KvVPgiQP28+3YRrRzOp+EYeietz72XUv0H3XJwRyJn/Sg7uzlrd5bEjYg6AoRkd0onbLM/QFJQk0WuqogLRPRteorSORwus4PKf0lsfVBp94i/8+UFxEIxUslAEZq57+23na5+7l83K8CxSPtoxax7/umaoB/MDhL40oZ35I="
    - secure: "i5AghXrGMOqMFmzvgOscXdF7aCeRO9Gk5J/barNpoOVZhJ2l4msq+TWCc846qujKgihsdqEs+8ESC5q42RMKgOVrmWqt0QxEMQAMP0HtTkyMkBELbBNcIeG4z46bDpELPeFxn5rXyBk9DxW1GLyKboJFJSEOtXnzwHeZydTiLL4="
    - secure: "j+JdQwGg/hOl+neQFEWks652qyAzCbK2Cm5J/ZttoE8/GJvoqbq4NITVMS4n44ZsrUfXRCoQgEPSfHfjiqbtcnt5AMP8D89e8CfqI2Ej45MPuiFbuGRlcO4FlmdgO4Y2Mw6h/w3AlG+38o2ZYURRCq0U56x8kUdSYoE4pbGrC7E="
    - secure: "cRmEMPw956cAmAEo4bOm3Pvp6lO8gGX90lTSew3rRfUACQA77Ojkem3K2EhMqxdD44HTODHsZoNT0u++GmX1hmENEWK5KBvHFNVO52vkQwpaU1aO3BAZ2Tkx0MwcT5WfTjPSdXsIAacKUfYLyVif2p+P4SpgA5ZYQbY+/2GmB30="
