language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - '4'
  - '5'
  - '6'
script:
  - npm test
  - ./travis.sh
cache:
  directories:
    - node_modules
env:
  global:
    - secure: "qV0+fFb4h/+cRt0XwuH1FMj2VaSJLv+gQZ+qq6QDQ1kZ+EnFYSMsDNgTENodwfjeC0TDb6PrMKrvzBGPLo4dUVUOqL5oQQLzD/EpuLbnZ0DlhaG4LZ2CyB4b7x3imxN4ay0szl2K/jE+zr5JOWSHIgqnrJ08NIW4TdPu+QOT/AY="
    - secure: "i5AghXrGMOqMFmzvgOscXdF7aCeRO9Gk5J/barNpoOVZhJ2l4msq+TWCc846qujKgihsdqEs+8ESC5q42RMKgOVrmWqt0QxEMQAMP0HtTkyMkBELbBNcIeG4z46bDpELPeFxn5rXyBk9DxW1GLyKboJFJSEOtXnzwHeZydTiLL4="
    - secure: "j+JdQwGg/hOl+neQFEWks652qyAzCbK2Cm5J/ZttoE8/GJvoqbq4NITVMS4n44ZsrUfXRCoQgEPSfHfjiqbtcnt5AMP8D89e8CfqI2Ej45MPuiFbuGRlcO4FlmdgO4Y2Mw6h/w3AlG+38o2ZYURRCq0U56x8kUdSYoE4pbGrC7E="
    - secure: "cRmEMPw956cAmAEo4bOm3Pvp6lO8gGX90lTSew3rRfUACQA77Ojkem3K2EhMqxdD44HTODHsZoNT0u++GmX1hmENEWK5KBvHFNVO52vkQwpaU1aO3BAZ2Tkx0MwcT5WfTjPSdXsIAacKUfYLyVif2p+P4SpgA5ZYQbY+/2GmB30="
